//! `PLAN.md` Track 24 Phase 3: the grammars this process can parse with,
//! supplied by whatever extensions registered rather than linked in here.
//!
//! What this replaces is a pair of `match`es over hardcoded language ids —
//! one returning a `tree_sitter::Language` from a statically linked grammar
//! crate, one returning an `include_str!`'d `.scm` query. Both are now
//! lookups into what `install` was handed, so adding a language to this
//! editor no longer means editing this crate: `crates/syntax` has stopped
//! depending on a single grammar crate, and the Java/Kotlin ones moved out
//! of the repository entirely (`../spring-foxgarden`).
//!
//! **Why a process-global store rather than a value threaded from the
//! registry.** Track 24's Checkpoint 0 already established the ownership
//! rule this has to obey: a loaded grammar's `Library` must outlive every
//! `Language` and every `Tree` derived from it, so nothing registered is
//! ever unregistered and everything installed here lives for the process.
//! Given that, a global is an honest model of the lifetime rather than a
//! shortcut around one — and the alternative (threading a handle into
//! `IncrementalParser::new` and `highlight_spans`) would plumb a parameter
//! through ~80 call sites, most of the way down the egui paint path, to
//! describe something that is genuinely per-process.
//!
//! **The hazard that buys, and its guard.** An editor that never calls
//! `install` parses nothing and highlights nothing, quietly — the same
//! shape of failure Phase 2 created with a languageless `EditorState`, and
//! answered the same way: the app installs at startup next to where it
//! builds the registry, `test_support` installs for the app's tests, and
//! this crate's own tests install the shipped set automatically (see
//! `store`), so a test that forgets is not a test that silently passes
//! while exercising nothing.

use std::collections::HashMap;
use std::ops::RangeInclusive;
use std::path::Path;
use std::sync::{OnceLock, RwLock};

use fg_core::Language;
use fg_extension::{GrammarSource, Registry};

/// Why one contributed grammar could not be installed.
///
/// Every variant names the language and the extension that contributed it,
/// because past Phase B the thing at fault is no longer necessarily this
/// codebase — the same reasoning `fg_extension::RegisterError` already
/// applies to registration refusals.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GrammarError {
    /// A shared-library grammar could not be opened, or exports no such
    /// entry symbol.
    Load {
        language_id: String,
        extension_id: String,
        message: String,
    },
    /// The grammar loaded but was generated by a tree-sitter this build
    /// cannot parse with.
    ///
    /// Its own variant rather than a `Load` message because it is the one
    /// failure with an actionable answer ("rebuild the grammar", "use a
    /// newer FoxGarden") and the one that will be common once grammars
    /// come from elsewhere — Track 24 Checkpoint 0 found the shipped Java
    /// grammar at ABI 14 against an accepted 13..=15, which is not much
    /// room.
    IncompatibleAbi {
        language_id: String,
        extension_id: String,
        found: usize,
        supported: RangeInclusive<usize>,
    },
}

impl std::fmt::Display for GrammarError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Load {
                language_id,
                extension_id,
                message,
            } => write!(
                f,
                "extension {extension_id}'s grammar for {language_id} could not be loaded: {message}"
            ),
            Self::IncompatibleAbi {
                language_id,
                extension_id,
                found,
                supported,
            } => write!(
                f,
                "extension {extension_id}'s grammar for {language_id} is ABI version {found}, but this build parses {}..={}",
                supported.start(),
                supported.end()
            ),
        }
    }
}

impl std::error::Error for GrammarError {}

/// The tree-sitter ABI versions this build can parse with.
fn supported_abi() -> RangeInclusive<usize> {
    tree_sitter::MIN_COMPATIBLE_LANGUAGE_VERSION..=tree_sitter::LANGUAGE_VERSION
}

/// One installed grammar: the parser itself plus the highlight query
/// source that was contributed alongside it.
///
/// The query is kept as source rather than compiled here because compiling
/// it is not free and most languages in a session are never opened — it
/// stays lazily compiled (and then cached forever) in `highlight.rs`,
/// exactly as it was before this module existed.
struct Installed {
    ts: tree_sitter::Language,
    highlight_query: Option<&'static str>,
}

type Store = RwLock<HashMap<Language, Installed>>;

fn store() -> &'static Store {
    static STORE: OnceLock<Store> = OnceLock::new();
    STORE.get_or_init(|| {
        #[allow(unused_mut)]
        let mut installed = HashMap::new();
        // This crate's own tests parse Java and Kotlin in a few hundred
        // places and none of them are about installation, so the shipped
        // set is installed for them here rather than at each call site.
        // Only ever compiled into a test build — `fg-languages` is a
        // dev-dependency, and depending on it for real would put back the
        // very edge this phase removed (`syntax` knowing which languages
        // exist).
        #[cfg(test)]
        install_into(&mut installed, &fg_languages::builtin_registry());
        RwLock::new(installed)
    })
}

/// Installs every grammar the registry holds, returning one error per
/// grammar that could not be installed.
///
/// Errors are returned rather than raised because one broken grammar is
/// not a reason to refuse to start: the language it belongs to degrades to
/// "opens and edits, paints plain", which is what any unrecognized file has
/// always done, and every other language still works. Installing twice is
/// harmless — a language already installed keeps the grammar it has, so a
/// second registry (a test's, or an extension enabled later) cannot swap a
/// parser out from under trees that already exist.
pub fn install(registry: &Registry) -> Vec<GrammarError> {
    let mut installed = store().write().expect("grammar store lock");
    install_into(&mut installed, registry)
}

fn install_into(installed: &mut HashMap<Language, Installed>, registry: &Registry) -> Vec<GrammarError> {
    let mut errors = Vec::new();
    for registered in registry.languages() {
        let Some(grammar) = &registered.grammar else { continue };
        let language = Language::new(registered.static_id);
        if installed.contains_key(&language) {
            continue;
        }
        match load(&grammar.source, &grammar.language_id, &registered.extension_id) {
            Ok(ts) => {
                installed.insert(
                    language,
                    Installed {
                        ts,
                        // Leaked, and bounded by the number of registered
                        // languages: the source has to outlive the query
                        // compiled from it, which lives as long as the
                        // grammar, which is the whole process.
                        highlight_query: grammar
                            .highlight_query
                            .clone()
                            .map(|q| &*Box::leak(q.into_boxed_str())),
                    },
                );
            }
            Err(error) => errors.push(error),
        }
    }
    errors
}

fn load(source: &GrammarSource, language_id: &str, extension_id: &str) -> Result<tree_sitter::Language, GrammarError> {
    let ts: tree_sitter::Language = match source {
        GrammarSource::Builtin(language_fn) => (*language_fn).into(),
        GrammarSource::SharedLibrary { path, symbol } => load_shared_library(path, symbol)
            .map_err(|message| GrammarError::Load {
                language_id: language_id.to_string(),
                extension_id: extension_id.to_string(),
                message,
            })?,
    };
    if !supported_abi().contains(&ts.abi_version()) {
        return Err(GrammarError::IncompatibleAbi {
            language_id: language_id.to_string(),
            extension_id: extension_id.to_string(),
            found: ts.abi_version(),
            supported: supported_abi(),
        });
    }
    Ok(ts)
}

/// Opens a grammar compiled as a shared object and hands back the
/// `Language` its entry symbol produces.
///
/// The library is deliberately never closed: a `Tree` parsed with this
/// grammar points into the library's own memory, so unloading it while any
/// tree is alive is a use-after-free. Track 24 Checkpoint 0's spike
/// established this constraint by modelling it (it leaked the `Library` on
/// purpose), which is also why hot-reloading a grammar is not a supported
/// operation.
///
/// Every failure here is a returned `Err`, never a crash — a missing file
/// and a missing entry symbol both come back as messages `install` reports
/// and carries on from, which is what makes it safe to let a registry point
/// at somebody else's `.so` at all.
fn load_shared_library(path: &Path, symbol: &str) -> Result<tree_sitter::Language, String> {
    // SAFETY: loading arbitrary native code is unsafe by nature — the
    // grammar's initializers run on load. This is the same trust boundary
    // Phase B's permission model has to reason about; nothing softer than
    // "only load what the user installed" is available at this layer.
    let library = unsafe { libloading::Library::new(path) }.map_err(|e| e.to_string())?;
    type EntryPoint = unsafe extern "C" fn() -> *const ();
    // SAFETY: the symbol is called immediately below and its result is
    // handed straight to `LanguageFn::from_raw`, which is the supported
    // seam for exactly this (Checkpoint 0 verified it against the pinned
    // tree-sitter). A wrong signature here is caught by tree-sitter's own
    // ABI check rather than by the loader.
    let entry = unsafe { library.get::<EntryPoint>(symbol.as_bytes()) }.map_err(|e| e.to_string())?;
    let language_fn = unsafe { tree_sitter_language::LanguageFn::from_raw(*entry) };
    let ts: tree_sitter::Language = language_fn.into();
    std::mem::forget(library);
    Ok(ts)
}

/// The tree-sitter grammar for `language`, or `None` if none was installed
/// for it.
///
/// `None` is a normal state, not an error: an extension may contribute a
/// language with no grammar at all, a grammar may have failed to load, or
/// nothing may have been installed yet. All three land on the same path an
/// unrecognized file has always taken — the document opens and edits with
/// no parse tree.
pub fn ts_language(language: Language) -> Option<tree_sitter::Language> {
    let installed = store().read().expect("grammar store lock");
    installed.get(&language).map(|g| g.ts.clone())
}

/// The highlight query source for `language`, or `None` if its extension
/// contributed none.
///
/// Independent of `ts_language` returning `Some`: a grammar with no query
/// parses fine and simply paints unhighlighted.
pub fn highlights_query_source(language: Language) -> Option<&'static str> {
    let installed = store().read().expect("grammar store lock");
    installed.get(&language)?.highlight_query
}

#[cfg(test)]
#[path = "grammars_test.rs"]
mod grammars_test;
