mod brackets;
mod diagnostics;
mod document_parser;
mod fields;
mod folding;
mod highlight;
mod language;
mod methods;
mod node_kinds;
mod selection;
mod sticky;

pub use brackets::bracket_match;
pub use diagnostics::syntax_errors;
pub use document_parser::{byte_to_point, diff_edit, IncrementalParser};
pub use fields::{java_classes_with_fields, ClassFields, FieldInfo};
pub use folding::{foldable_ranges, FoldRange};
pub use highlight::{highlight_spans, Scope};
pub use methods::{enclosing_class, methods_in_type, superclass_name, MethodSignature};
pub use selection::expand_selection;
pub use sticky::enclosing_scope_starts;
pub use tree_sitter::{InputEdit, Point, Tree};
